stages:
  preprocess:
    cmd: python src/preprocess.py params.yaml data/data_prep.csv models/prep.pkl
    deps:
    - params.yaml
    outs:
    - data/data_prep.csv
    - models/prep.pkl
  train:
    cmd: python src/train.py data/data_prep.csv models/best_model.pkl params.yaml
    deps:
    - data/data_prep.csv
    - params.yaml
    outs:
    - models/best_model.pkl
  evaluate:
    cmd: python src/evaluate.py data/data_prep.csv models/best_model.pkl metrics.json
      params.yaml
    deps:
    - data/data_prep.csv
    - models/best_model.pkl
    - params.yaml
    metrics:
    - metrics.json:
        cache: false
